// Generated by js_of_ocaml 3.0.1
(function(d){"use strict";var
ar=" : flags Open_text and Open_binary are not compatible",ab="Sys_error",aq=224,ap="Invalid_argument",r=1024,ao="fs",F="jsError",aa=57343,an=512,am="End_of_file",al="Failure",_="Undefined_recursive_module",$=" : flags Open_rdonly and Open_wronly are not compatible",Z="([^/]*)",aj="btn_click",ak="Stack_overflow",g=128,b="",E="^",V=" : file already exists",W=2048,X=56320,Y=240,f=248,ah="Not_found",ai="undefined",U="Assert_failure",m="/",af="Sys_blocked_io",ag="fd ",T="Out_of_memory",ae="Match_failure",ac="Division_by_zero",ad="static/";function
bc(c,e){var
d=c.length,b=new
Array(d+1),a=0;for(;a<d;a++)b[a]=c[a];b[a]=e;return b}function
K(d,e,c){var
b=new
Array(c);for(var
a=0;a<c;a++)b[a]=d[e+a];return b}function
z(b,a){if(b.fun)return z(b.fun,a);var
c=b.length,d=a.length,e=c-d;if(e==0)return b.apply(null,a);else
if(e<0)return z(b.apply(null,K(a,0,c)),K(a,c,d-c));else
return function(c){return z(b,bc(a,c))}}var
aY=0;function
t(){return aY++}function
aw(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>127)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
a_(f){for(var
h=b,c=h,a,j,d=0,i=f.length;d<i;d++){a=f.charCodeAt(d);if(a<g){for(var
e=d+1;e<i&&(a=f.charCodeAt(e))<g;e++);if(e-d>an){c.substr(0,1);h+=c;c=b;h+=f.slice(d,e)}else
c+=f.slice(d,e);if(e==i)break;d=e}if(a<W){c+=String.fromCharCode(192|a>>6);c+=String.fromCharCode(g|a&63)}else
if(a<55296||a>=aa)c+=String.fromCharCode(aq|a>>12,g|a>>6&63,g|a&63);else
if(a>=56319||d+1==i||(j=f.charCodeAt(d+1))<X||j>aa)c+="\xef\xbf\xbd";else{d++;a=(a<<10)+j-56613888;c+=String.fromCharCode(Y|a>>18,g|a>>12&63,g|a>>6&63,g|a&63)}if(c.length>r){c.substr(0,1);h+=c;c=b}}return h+c}function
a2(c,a){if(a.repeat)return a.repeat(c);var
d=b,e=0;if(c==0)return d;for(;;){if(c&1)d+=a;c>>=1;if(c==0)return d;a+=a;e++;if(e==9)a.slice(0,1)}}function
J(c,d,a){var
e=String.fromCharCode;if(d==0&&a<=4096&&a==c.length)return e.apply(null,c);var
f=b;for(;0<a;d+=r,a-=r)f+=e.apply(null,K(c,d,Math.min(a,r)));return f}function
au(a){if(a.t==2)a.c+=a2(a.l-a.c.length,"\0");else
a.c=J(a.c,0,a.c.length);a.t=0}function
a9(f){for(var
l=b,d=b,i,h,j,a,c=0,k=f.length;c<k;c++){h=f.charCodeAt(c);if(h<g){for(var
e=c+1;e<k&&(h=f.charCodeAt(e))<g;e++);if(e-c>an){d.substr(0,1);l+=d;d=b;l+=f.slice(c,e)}else
d+=f.slice(c,e);if(e==k)break;c=e}a=1;if(++c<k&&((j=f.charCodeAt(c))&-64)==g){i=j+(h<<6);if(h<aq){a=i-12416;if(a<g)a=1}else{a=2;if(++c<k&&((j=f.charCodeAt(c))&-64)==g){i=j+(i<<6);if(h<Y){a=i-925824;if(a<W||a>=55295&&a<57344)a=2}else{a=3;if(++c<k&&((j=f.charCodeAt(c))&-64)==g&&h<245){a=j-63447168+(i<<6);if(a<65536||a>1114111)a=3}}}}}if(a<4){c-=a;d+="\ufffd"}else
if(a>65535)d+=String.fromCharCode(55232+(a>>10),X+(a&1023));else
d+=String.fromCharCode(a);if(d.length>r){d.substr(0,1);l+=d;d=b}}return l+d}function
a8(a){switch(a.t){case
9:return a.c;default:au(a);case
0:if(aw(a.c)){a.t=9;return a.c}a.t=8;case
8:return a9(a.c)}}function
n(c,a,b){this.t=c;this.c=a;this.l=b}n.prototype.toString=function(){return a8(this)};function
I(a){var
b=9;if(!aw(a))b=8,a=a_(a);return new
n(b,a,a.length)}function
a0(b,a){throw[0,b,a]}function
a(a){return new
n(0,a,a.length)}function
aB(c,b){a0(c,a(b))}var
c=[0];function
j(a){aB(c.Sys_error,a)}var
o=new
Array();function
aU(e){var
a=o[e];if(!a.opened)j("Cannot flush a closed channel");if(!a.buffer||a.buffer==b)return 0;if(a.fd&&c.fds[a.fd]&&c.fds[a.fd].output){var
d=c.fds[a.fd].output;switch(d.length){case
2:d(e,a.buffer);break;default:d(a.buffer)}}a.buffer=b;return 0}if(d.process&&d.process.cwd)var
s=d.process.cwd().replace(/\\/g,m);else
var
s="/static";if(s.slice(-1)!==m)s+=m;function
aT(a){a=a
instanceof
n?a.toString():a;if(a.charCodeAt(0)!=47)a=s+a;var
e=a.split(m),c=[];for(var
d=0;d<e.length;d++)switch(e[d]){case"..":if(c.length>1)c.pop();break;case".":break;case"":if(c.length==0)c.push(b);break;default:c.push(e[d]);break}c.orig=a;return c}function
aZ(a){a=a
instanceof
n?a.toString():a;j(a+": No such file or directory")}function
a4(a){return new
n(4,a,a.length)}function
av(a){aB(c.Invalid_argument,a)}function
aE(){av("index out of bounds")}function
a6(a,b){switch(a.t&6){default:if(b>=a.c.length)return 0;case
0:return a.c.charCodeAt(b);case
4:return a.c[b]}}function
a3(b,a){if(a>>>0>=b.l)aE();return a6(b,a)}function
p(a){if(a<0)av("String.create");return new
n(a?2:9,b,a)}function
ay(a){return a.l}function
H(b){if(d.Uint8Array)var
c=new(d.Uint8Array)(b.l);else
var
c=new
Array(b.l);var
f=b.c,e=f.length,a=0;for(;a<e;a++)c[a]=f.charCodeAt(a);for(e=b.l;a<e;a++)c[a]=0;b.c=c;b.t=4;return c}function
y(d,e,b,f,c){if(c==0)return 0;if(f==0&&(c>=b.l||b.t==2&&c>=b.c.length)){b.c=d.t==4?J(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else
if(b.t==2&&f==b.c.length){b.c+=d.t==4?J(d.c,e,c):e==0&&d.c.length==c?d.c:d.c.substr(e,c);b.t=b.c.length==b.l?0:2}else{if(b.t!=4)H(b);var
g=d.c,h=b.c;if(d.t==4)if(f<=e)for(var
a=0;a<c;a++)h[f+a]=g[e+a];else
for(var
a=c-1;a>=0;a--)h[f+a]=g[e+a];else{var
i=Math.min(c,g.length-e);for(var
a=0;a<i;a++)h[f+a]=g.charCodeAt(e+a);for(;a<c;a++)h[f+a]=0}}return 0}function
as(){}function
e(a){this.data=a}e.prototype=new
as();e.prototype.truncate=function(a){var
b=this.data;this.data=p(a|0);y(b,0,this.data,0,a)};e.prototype.length=function(){return ay(this.data)};e.prototype.write=function(b,d,g,a){var
c=this.length();if(b+a>=c){var
e=p(b+a),f=this.data;this.data=e;y(f,0,this.data,0,c)}y(d,g,this.data,b,a);return 0};e.prototype.read=function(c,a,d,b){var
e=this.length();y(this.data,c,a,d,b);return 0};e.prototype.read_one=function(a){return a3(this.data,a)};e.prototype.close=function(){};e.prototype.constructor=e;function
h(b,a){this.content={};this.root=b;this.lookupFun=a}h.prototype.nm=function(a){return this.root+a};h.prototype.lookup=function(b){if(!this.content[b]&&this.lookupFun){var
c=this.lookupFun(a(this.root),a(b));if(c!=0)this.content[b]=new
e(c[1])}};h.prototype.exists=function(a){if(a==b)return 1;var
d=a+m,e=new
RegExp(E+d);for(var
c
in
this.content)if(c.match(e))return 1;this.lookup(a);return this.content[a]?1:0};h.prototype.readdir=function(d){var
g=d==b?b:d+m,h=new
RegExp(E+g+Z),e={},c=[];for(var
f
in
this.content){var
a=f.match(h);if(a&&!e[a[1]]){e[a[1]]=true;c.push(a[1])}}return c};h.prototype.is_dir=function(a){var
e=a==b?b:a+m,f=new
RegExp(E+e+Z),g=[];for(var
d
in
this.content){var
c=d.match(f);if(c)return 1}return 0};h.prototype.unlink=function(a){var
b=this.content[a]?true:false;delete
this.content[a];return b};h.prototype.open=function(a,b){if(b.rdonly&&b.wronly)j(this.nm(a)+$);if(b.text&&b.binary)j(this.nm(a)+ar);this.lookup(a);if(this.content[a]){if(this.is_dir(a))j(this.nm(a)+" : is a directory");if(b.create&&b.excl)j(this.nm(a)+V);var
c=this.content[a];if(b.truncate)c.truncate();return c}else
if(b.create){this.content[a]=new
e(p(0));return this.content[a]}else
aZ(this.nm(a))};h.prototype.register=function(c,b){if(this.content[c])j(this.nm(c)+V);if(b
instanceof
n)this.content[c]=new
e(b);else
if(b
instanceof
Array)this.content[c]=new
e(a4(b));else
if(b.toString){var
d=a(b.toString());this.content[c]=new
e(d)}};h.prototype.constructor=h;function
at(a){if(a.t!=4)H(a);return a.c}function
a7(a,c,b){b&=255;if(a.t!=4){if(c==a.c.length){a.c+=String.fromCharCode(b);if(c+1==a.l)a.t=0;return 0}H(a)}a.c[c]=b;return 0}function
a5(b,a,c){if(a>>>0>=b.l)aE();return a7(b,a,c)}var
G=d.Buffer;function
l(a){this.fs=require(ao);this.fd=a}l.prototype=new
as();l.prototype.truncate=function(a){this.fs.ftruncateSync(this.fd,a|0)};l.prototype.length=function(){return this.fs.fstatSync(this.fd).size};l.prototype.write=function(g,b,c,f){var
a=at(b);if(!a
instanceof
d.Uint8Array)a=new(d.Uint8Array)(a);var
e=new
G(a);this.fs.writeSync(this.fd,e,c,f,g);return 0};l.prototype.read=function(h,e,c,g){var
a=at(e);if(!(a
instanceof
d.Uint8Array))a=new(d.Uint8Array)(a);var
f=new
G(a);this.fs.readSync(this.fd,f,c,g,h);for(var
b=0;b<g;b++)a5(e,c+b,f[c+b]);return 0};l.prototype.read_one=function(c){var
b=new(d.Uint8Array)(1),a=new
G(b);this.fs.readSync(this.fd,a,0,1,c);return a[0]};l.prototype.close=function(){this.fs.closeSync(this.fd)};l.prototype.constructor=l;function
k(a){this.fs=require(ao);this.root=a}k.prototype.nm=function(a){return this.root+a};k.prototype.exists=function(a){return this.fs.existsSync(this.nm(a))?1:0};k.prototype.readdir=function(a){return this.fs.readdirSync(this.nm(a))};k.prototype.is_dir=function(a){return this.fs.statSync(this.nm(a)).isDirectory()?1:0};k.prototype.unlink=function(a){var
b=this.fs.existsSync(this.nm(a))?1:0;this.fs.unlinkSync(this.nm(a));return b};k.prototype.open=function(f,c){var
a=require("constants"),b=0;for(var
e
in
c)switch(e){case"rdonly":b|=a.O_RDONLY;break;case"wronly":b|=a.O_WRONLY;break;case"append":b|=a.O_WRONLY|a.O_APPEND;break;case"create":b|=a.O_CREAT;break;case"truncate":b|=a.O_TRUNC;break;case"excl":b|=a.O_EXCL;break;case"binary":b|=a.O_BINARY;break;case"text":b|=a.O_TEXT;break;case"nonblock":b|=a.O_NONBLOCK;break}var
d=this.fs.openSync(this.nm(f),b);return new
l(d)};k.prototype.rename=function(b,a){this.fs.renameSync(this.nm(b),this.nm(a))};k.prototype.constructor=k;var
q=s.match(/[^\/]*\//)[0],u=[];if(typeof
module!==ai&&module.exports&&typeof
require!==ai)u.push({path:q,device:new
k(q)});else
u.push({path:q,device:new
h(q)});u.push({path:q+ad,device:new
h(q+ad)});function
bd(b){var
f=aT(b),b=f.join(m),e=b+m,c;for(var
d=0;d<u.length;d++){var
a=u[d];if(e.search(a.path)==0&&(!c||c.path.length<a.path.length))c={path:a.path,device:a.device,rest:b.substring(a.path.length,b.length)}}return c}function
aD(e,f){var
b=o[e],d=a(f),c=ay(d);b.file.write(b.offset,d,0,c);b.offset+=c;return 0}function
ba(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stderr.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.error&&c.error(a)}}function
bb(a){var
b=d;if(b.process&&b.process.stdout&&b.process.stdout.write)b.process.stdout.write(a);else{if(a.charCodeAt(a.length-1)==10)a=a.substr(0,a.length-1);var
c=b.console;c&&c.log&&c.log(a)}}function
A(d,f,e,a){if(c.fds===undefined)c.fds=new
Array();a=a?a:{};var
b={};b.file=e;b.offset=a.append?e.length():0;b.flags=a;b.output=f;c.fds[d]=b;if(!c.fd_last_idx||d>c.fd_last_idx)c.fd_last_idx=d;return d}function
be(d,b,h){var
a={};while(b){switch(b[1]){case
0:a.rdonly=1;break;case
1:a.wronly=1;break;case
2:a.append=1;break;case
3:a.create=1;break;case
4:a.truncate=1;break;case
5:a.excl=1;break;case
6:a.binary=1;break;case
7:a.text=1;break;case
8:a.nonblock=1;break}b=b[2]}if(a.rdonly&&a.wronly)j(d.toString()+$);if(a.text&&a.binary)j(d.toString()+ar);var
e=bd(d),f=e.device.open(e.rest,a),g=c.fd_last_idx?c.fd_last_idx:0;return A(g+1,aD,f,a)}A(0,aD,new
e(p(0)));A(1,bb,new
e(p(0)));A(2,ba,new
e(p(0)));function
aV(d){var
b=c.fds[d];if(b.flags.wronly)j(ag+d+" is writeonly");var
a={file:b.file,offset:b.offset,fd:d,opened:true,out:false,refill:null};o[a.fd]=a;return a.fd}function
ax(e){var
d=c.fds[e];if(d.flags.rdonly)j(ag+e+" is readonly");var
a={file:d.file,offset:d.offset,fd:e,opened:true,out:true,buffer:b};o[a.fd]=a;return a.fd}function
aW(){var
b=0;for(var
a=0;a<o.length;a++)if(o[a]&&o[a].opened&&o[a].out)b=[0,o[a].fd,b];return b}function
aX(a){return a
instanceof
Array?a[0]:a
instanceof
n?252:1e3}function
i(d,b,a){c[d+1]=b;if(a)c[a]=b}var
aA={};function
aS(a){if((a.t&6)!=0)au(a);return a.c}function
a1(a,b){aA[aS(a)]=b;return 0}function
aC(a){return a}function
az(a){return aA[a]}function
a$(a){if(a
instanceof
Array)return a;if(d.RangeError&&a
instanceof
d.RangeError&&a.message&&a.message.match(/maximum call stack/i))return aC(c.Stack_overflow);if(d.InternalError&&a
instanceof
d.InternalError&&a.message&&a.message.match(/too much recursion/i))return aC(c.Stack_overflow);if(a
instanceof
d.Error&&az(F))return[0,az(F),a];return[0,c.Failure,I(String(a))]}function
S(a,b){return a.length==1?a(b):z(a,[b])}var
M=[f,a(ab),-2],L=[f,a(al),-3],N=[f,a(ah),-7];i(11,[f,a(_),-12],_);i(10,[f,a(U),-11],U);i(9,[f,a(af),-10],af);i(8,[f,a(ak),-9],ak);i(7,[f,a(ae),-8],ae);i(6,N,ah);i(5,[f,a(ac),-6],ac);i(4,[f,a(am),-5],am);i(3,[f,a(ap),-4],ap);i(2,L,al);i(1,M,ab);i(0,[f,a(T),-1],T);t(0);aV(0);ax(1);ax(2);t(0);t(0);var
O=[0,0],aJ=a("Js.Error"),aP=a("erreur"),aN=a("click_number"),aO=a(aj),aL=a(aj),aQ=a("btn_alert");function
P(a){O[1]=[0,a,O[1]];return 0}var
v=d,w=null,B=true,aI=v.Array,Q=[f,aJ,t(0)],C=[0,Q,{}],aH=undefined,aG=aX(C)===f?C:C[1];a1(a(F),aG);(function(a){throw a});P(function(a){return a[1]===Q?[0,I(a[2].toString())]:0});P(function(a){return a
instanceof
aI?0:[0,I(a.toString())]});function
R(c){return function(a){if(1-(a==w?1:0)){var
d=S(c,a);if(1-(d|0))a.preventDefault();return d}var
e=event,b=S(c,e);if(1-(b|0))e.returnValue=b;return b}}var
aK=v.document;function
x(b){var
a=aK.getElementById(b.toString());if(a==w)throw N;return a}t(0);v.HTMLElement===aH;var
D=[0,0],aM=x(aL);aM.onclick=R(function(g){D[1]=D[1]+1|0;var
c=D[1],f=a(b+c).toString();x(aN).innerHTML=f;if(10<=c){var
d=x(aO),e=d.tagName.toLowerCase()==="button"?d:w;if(e==w)throw[0,L,aP];e.disabled=B}return B});var
aR=x(aQ);aR.onclick=R(function(a){v.alert("Alerte!");return B});function
aF(b){var
a=b;for(;;){if(a){var
c=a[2],d=a[1];try{aU(d)}catch(a){a=a$(a);if(a[1]!==M)throw a}var
a=c;continue}return 0}}aF(aW(0));return}(function(){return this}()));
